- merging work from kdepim-3.5.5+/kpilot branch (and codeyard's kpilot svn   repo) into main 3.5 branch.  merge is -r597269:611836 from   /branches/work/kdepim-3.5.5+. - all development work for kpilot for the past year present here,   including:   - new state machine in vcalconduit   - new standalone out-of-source build system, via cmake   - bug fixes   - code cleanup and refactoring   - new test case directory structure and some semi-useful test cases   - removal of malconduit (doesn't compile thanks to libmal changes, also     none of the developers use it)   - removing fastSync and separating backup options from syncing options.     small string changes because of this (necessary for bug fixes).   - minimum pilot-link requirement now is 0.12.1   - this major merge should solve the data loss problems that ubuntu,     mandrake, and debian users have been reporting.
svn path=/branches/KDE/3.5/kdepim/; revision=611839

diff --git a/kpilot/lib/Makefile.am b/kpilot/lib/Makefile.am
--- a/kpilot/lib/Makefile.am
+++ b/kpilot/lib/Makefile.am
@@ -16,48 +16,33 @@ INCLUDES = $(PISOCK_INCLUDE) -I$(top_srcdir) $(all_includes)
 
 lib_LTLIBRARIES = libkpilot.la
 
-libkpilot_la_SOURCES = kpilotlibSettings.kcfgc options.cc uiDialog.cc plugin.cc syncAction.cc \
+libkpilot_la_SOURCES = kpilotlibSettings.kcfgc \
+	options.cc uiDialog.cc plugin.cc syncAction.cc \
 	kpilotlink.cc \
-	pilotRecord.cc pilotDatabase.cc \
+	pilot.cc \
+	pilotAppInfo.cc pilotRecord.cc pilotDatabase.cc \
 	pilotLocalDatabase.cc pilotSerialDatabase.cc \
 	pilotMemo.cc pilotAddress.cc \
 	pilotDateEntry.cc pilotTodoEntry.cc \
-	recordConduit.cc
+	pilotStruct.cc
 
-libkpilot_la_LDFLAGS = -no-undefined $(PISOCK_LDFLAGS) $(all_libraries) $(KDE_EXTRA_RPATH) $(KDE_RPATH)
-libkpilot_la_LIBADD = $(LIB_KDEUI) $(PISOCK_LIB) $(LIB_KABC) $(top_builddir)/libkcal/libkcal.la
+libkpilot_la_LDFLAGS = $(PISOCK_LDFLAGS) -no-undefined $(all_libraries) $(KDE_EXTRA_RPATH) $(KDE_RPATH)
+libkpilot_la_LIBADD = $(PISOCK_LIB) $(LIB_KDEUI) $(LIB_KABC) $(top_builddir)/libkcal/libkcal.la
 
 kpilotincludedir = $(includedir)/kpilot
 kpilotinclude_HEADERS = kpilotlink.h uiDialog.h \
 	plugin.h pluginfactory.h syncAction.h \
 	pilotRecord.h pilotDatabase.h \
-	pilotLocalDatabase.h pilotSerialDatabase.h \
-	pilotLinkVersion.h
+	pilotLocalDatabase.h pilotSerialDatabase.h
 
 kde_kcfg_DATA = kpilotlib.kcfg
-
-check_PROGRAMS = testactions testconstants testdatabase
-TESTS = testactions testconstants testdatabase
-
-testactions_SOURCES = testactions.cc
-testactions_LDFLAGS = $(PISOCK_LDFLAGS) $(all_libraries) $(KDE_RPATH)
-testactions_LDADD  = libkpilot.la $(PISOCK_LIB)
-
-testconstants_SOURCES = testconstants.cc
-testconstants_LDFLAGS = $(PISOCK_LDFLAGS) $(all_libraries) $(KDE_RPATH)
-testconstants_LDADD   = libkpilot.la $(PISOCK_LIB)
-
-testdatabase_SOURCES  = testdatabase.cc
-testdatabase_LDFLAGS  = $(PISOCK_LDFLAGS) $(all_libraries) $(KDE_RPATH)
-testdatabase_LDADD    = libkpilot.la $(PISOCK_LIB)
-testdatabase_CXXFLAGS = '-DSOURCE="$(srcdir)"'
 
 check-local:
 	rm -f FAILED
 	for i in $(srcdir)/*.h ; do \
 		( echo "#include <kdemacros.h>" ; echo "#include \"$$i\"" ; echo "int main(int argc,char **argv){return 0;}" ) > header-test.cc; \
 		echo "$$i" ; \
-		g++ $(all_includes) $(PISOCK_INCLUDE) -c header-test.cc || echo "$$i" >> FAILED; \
+		g++ $(all_includes) -c header-test.cc || echo "$$i" >> FAILED; \
 	done
 	test ! -e FAILED
 
