- merging all development and bug fixes from kdepim-3.5.5+ branch into   stable branches/KDE/3.5 in preparation for KDE 3.5.7 - cmake cleanups - namespacing and cleanups in sysinfoconduit - lots of debugging cleanups.  remove #ifdef DEBUG from much of the code. - cleanups in memofile conduit.  now try to use new (OS5) database   (MemosDB-PMem) if it's found, otherwise fall back to the legacy one   (MemoDB) - as a first step to combatting the "kpilot ate my future" e-mails (read:   data loss), we now use a CUDCounter (Create/Update/Delete). step 1 is to   track these and report on them to the user in their sync log.  step 2 is   to catch ill behavior and prompt the user as to whether or not to allow   kpilot to make the large amount of changes.  step 3 is to allow the user   to configure the count or percentage of changes that kpilot can make   without his/her confirmation.  step 1 is done. we'll approach steps 2 and   3 post kde 3.5.7. - new strings related to the above CCMAIL:kde-i18n-doc@kde.org - bug fixing in popconduit... making sure we always have a sent date - Bertjan has the start of knotes cleanup going on - bug fixing in vcalconduit... long-time bug that existed in libkcal that   caused every calendar resource save to mark every calendar event as   modified.  now kpilot won't have to sync every record every time. - bug fixing kabc resource problems in abbrowser conduit.  although it's   not documented in kabc, it looks like we should be removing a local   resource from the address book before we delete it. - bringing mal conduit back alive again.  none of our small band of merry   men use it, though, so it may or may not actually do what it's supposed   to. - fixing bug where we were saving conduit databases to DBBackup instead of   conduits/ directory. - changing KPilotDeviceLink to use a separate thread, dedicated to doing   device communication.  this is much better design as a start, but fixes   the problems kpilot was having (and widely talked about) where kpilot   would hang and crash if our user was using "usb:" or "net:any" devices   because of how these new "device"s operated (allowed immediate opening,   even though there is no physical device connected, and then hung   indefinitely until the real device connected). - bringing in design documents (jpegs) for memofile conduit from 2004-12-12   (they're not installed, but are valuable for documentation and insight) - icon naming error bug fix 122582
svn path=/branches/KDE/3.5/kdepim/; revision=654396

diff --git a/kpilot/configure b/kpilot/configure
--- a/kpilot/configure
+++ b/kpilot/configure
@@ -3,7 +3,8 @@
 # simple configure script for user-friendliness
 
 # file to put output into for cmake to read in...
-OUTFILE=$(dirname $0)/CMakeOptions.txt
+OUTFILE=$(dirname $0)/Makefile.cmake.in
+CMAKEOUTFILE=$(dirname $0)/CMakeOptions.txt
 
 # --- FUNCTIONS ---
 
@@ -41,7 +42,8 @@ getvalue()
 	
 	if test -n "$VAL"
 	then
-		CMAKE_FLAGS="${CMAKE_FLAGS}-D${KEY}=${VAL} "
+		CMAKE_FLAGS="${CMAKE_FLAGS}set(${KEY} \"${VAL}\")
+"
 		if [ "$ECHO" = "y" ]
 		then
 			echo "$KEY=\"$VAL\""
@@ -50,22 +52,27 @@ getvalue()
 
 }
 
-outputvalues()
+outputCmakeValues()
 {
 
 # only include what we're passed
 CMAKE_FLAGS=""
 
-getvalue CMAKE_INSTALL_PREFIX y
-getvalue CMAKE_BUILD_TYPE y
-getvalue ENABLE_TESTS y
-getvalue BUILD_DIR y
-getvalue PILOTLINK_BASE y
-getvalue MAL_BASE y
-getvalue PILOTLINK_INCLUDE_DIR y
-getvalue PILOTLINK_LIBRARY y
+getvalue CMAKE_INSTALL_PREFIX n
+getvalue CMAKE_BUILD_TYPE n
+getvalue ENABLE_TESTS n
+#getvalue BUILD_DIR y
+getvalue PILOTLINK_BASE n
+getvalue MAL_BASE n
+getvalue PILOTLINK_INCLUDE_DIR n
+getvalue PILOTLINK_LIBRARY n
 
-echo "CMAKE_FLAGS=$CMAKE_FLAGS"
+echo "$CMAKE_FLAGS"
+}
+
+outputMakeValues()
+{
+getvalue BUILD_DIR y
 }
 
 # --- MAIN ---
@@ -79,6 +86,7 @@ fi
 
 CMAKE_BUILD_TYPE="normal"
 ENABLE_TESTS="NO"
+BUILD_DIR=build-`uname -sr | tr -d [:space:] | tr -Cs a-zA-Z0-9 _`
 
 while test -n "$1"
 do
@@ -122,7 +130,9 @@ do
 			;;
 		--show)
 			echo "Existing configuration values:"
+			echo "-----------"
 			cat "$OUTFILE" 2>/dev/null
+			sed 's/^set(\([A-Z_]*\) "\(.*\)")/\1="\2"/' "$CMAKEOUTFILE" 2>/dev/null
 			echo "-----------"
 			exit
 			;;
@@ -136,26 +146,18 @@ do
 
 done
 
-echo "
-Thanks.  Here are the values I will be using...
-
-$(outputvalues)
-
-To compile KPilot, now run GNU make, like so:
-"
-
 ###
 #
 # BSD uses gmake for the GNU make which we need ...
 #
 if uname -s | grep BSD > /dev/null 2>&1 ; then
-	echo "    gmake -f Makefile.cmake"
+	MAKE=gmake
 else
-	echo "    make -f Makefile.cmake"
+	MAKE=make
 fi
-echo ""
 
-outputvalues > "$OUTFILE.new"
+outputCmakeValues > "$CMAKEOUTFILE.new"
+outputMakeValues > "$OUTFILE.new"
 
 
 ###
@@ -164,15 +166,48 @@ outputvalues > "$OUTFILE.new"
 # CMakeLists.txt in order to prompt a re-run of cmake.
 #
 update=no
+failed=no
+if test -f "$CMAKEOUTFILE" ; then
+	diff -q "$CMAKEOUTFILE" "$CMAKEOUTFILE.new" > /dev/null 2>&1 || update=yes
+else
+	update=yes
+fi
+
 if test -f "$OUTFILE" ; then
 	diff -q "$OUTFILE" "$OUTFILE.new" > /dev/null 2>&1 || update=yes
 else
 	update=yes
 fi
+
 if test yes = "$update" ; then
+	cp "$CMAKEOUTFILE.new" "$CMAKEOUTFILE"
 	cp "$OUTFILE.new" "$OUTFILE"
 	touch CMakeLists.txt
+	$MAKE -f Makefile.cmake build-check || failed=yes
 fi
-rm -f "$OUTFILE.new"
 
+rm -f "$CMAKEOUTFILE.new"
+rm -f "$OUTFILE.new"
+rm -f build*/CMakeCache.txt
+
+###
+#
+# Inform user and create settings file.
+#
+echo "
+Thanks.  Here are the values I will be using...
+
+$(outputCmakeValues)
+
+$(outputMakeValues)
+
+To compile KPilot, now run GNU make, like so:
+
+    $MAKE -f Makefile.cmake
+
+"
+
+if test "yes" = "$failed" ; then
+	echo "Configuration failed, so take a good look at the build output."
+fi
 
diff --git a/kpilot/lib/Makefile.am b/kpilot/lib/Makefile.am
--- a/kpilot/lib/Makefile.am
+++ b/kpilot/lib/Makefile.am
@@ -17,8 +17,9 @@ INCLUDES = $(PISOCK_INCLUDE) -I$(top_srcdir) $(all_includes)
 lib_LTLIBRARIES = libkpilot.la
 
 libkpilot_la_SOURCES = kpilotlibSettings.kcfgc \
-	options.cc uiDialog.cc plugin.cc syncAction.cc \
-	kpilotlink.cc \
+	options.cc plugin.cc syncAction.cc \
+	kpilotlink.cc kpilotdevicelink.cc kpilotlocallink.cc \
+	actions.cc actionQueue.cc \
 	pilot.cc \
 	pilotAppInfo.cc pilotRecord.cc pilotDatabase.cc \
 	pilotLocalDatabase.cc pilotSerialDatabase.cc \
@@ -32,7 +33,7 @@ libkpilot_la_LIBADD = $(PISOCK_LIB) $(LIB_KDEUI) $(LIB_KABC) $(top_builddir)/lib
 
 kpilotincludedir = $(includedir)/kpilot
 kpilotinclude_HEADERS = \
-	kpilotlink.h \
+	kpilotlink.h kpilotlocallink.h kpilotdevicelink.h \
 	pilot.h \
 	pilotDatabase.h \
 	pilotLinkVersion.h \
@@ -41,8 +42,7 @@ kpilotinclude_HEADERS = \
 	pilotSerialDatabase.h \
 	plugin.h \
 	pluginfactory.h \
-	syncAction.h \
-	uiDialog.h
+	syncAction.h
 
 
 kde_kcfg_DATA = kpilotlib.kcfg
@@ -52,7 +52,7 @@ check-local:
 	for i in $(srcdir)/*.h ; do \
 		( echo "#include <kdemacros.h>" ; echo "#include \"$$i\"" ; echo "int main(int argc,char **argv){return 0;}" ) > header-test.cc; \
 		echo "$$i" ; \
-		g++ $(all_includes) -c header-test.cc || echo "$$i" >> FAILED; \
+		g++ $(all_includes) -I$(top_builddir) -c header-test.cc || echo "$$i" >> FAILED; \
 	done
 	test ! -e FAILED
 
